# Generated by Django 4.2 on 2023-04-16 09:35

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="характеристика",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Группа характеристик"),
                            (1, "Элемент списка"),
                            (2, "Измерение"),
                        ],
                        default=0,
                        verbose_name="тип",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="модель")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=main.utilities.get_timestamp_path,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="модель доступна?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="опубликовано"
                    ),
                ),
            ],
            options={
                "verbose_name": "модель",
                "verbose_name_plural": "модели",
            },
        ),
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.utilities.get_timestamp_path,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="модель",
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительное изображение",
                "verbose_name_plural": "дополнительные изображения",
            },
        ),
        migrations.CreateModel(
            name="CharacteristicGroup",
            fields=[],
            options={
                "verbose_name": "группа характеристик",
                "verbose_name_plural": "группы характеристик",
                "ordering": ("order", "title"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.characteristic",),
        ),
        migrations.CreateModel(
            name="CharacteristicItem",
            fields=[],
            options={
                "verbose_name": "характеристика",
                "verbose_name_plural": "характеристики",
                "ordering": ("group__order", "group__title", "order", "title"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.characteristic",),
        ),
        migrations.AddField(
            model_name="characteristic",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.characteristicgroup",
                verbose_name="надрубрика",
            ),
        ),
    ]
