# Generated by Django 4.2 on 2023-05-07 13:20

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.utilities.get_timestamp_path,
                verbose_name="основное изображение",
            ),
        ),
    ]
