# Generated by Django 4.2 on 2023-04-19 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.CreateModel(
            name="UserProductRelated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_on_cart",
                    models.PositiveIntegerField(default=0, verbose_name="в корзине"),
                ),
                (
                    "is_favorit",
                    models.BooleanField(default=False, verbose_name="избранное"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(
                through="main.UserProductRelated", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
