# Generated by Django 4.2 on 2023-04-16 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristic",
            name="title",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="характеристика"
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Группа характеристик"),
                    (1, "Элемент списка"),
                    (2, "Измерение"),
                ],
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="тип",
            ),
        ),
        migrations.AddConstraint(
            model_name="characteristic",
            constraint=models.UniqueConstraint(
                models.OrderBy(
                    django.db.models.functions.text.Lower("title"), descending=True
                ),
                models.F("group"),
                name="unique_lower_name_category",
            ),
        ),
    ]
