# Generated by Django 4.2 on 2023-04-19 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_product_options_userproductrelated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="buyers",
        ),
    ]
