# Generated by Django 4.2 on 2023-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_characteristic_title_alter_characteristic_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacteristicProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(null=True, verbose_name="значение")),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.characteristicitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="characteristics",
            field=models.ManyToManyField(
                through="main.CharacteristicProduct", to="main.characteristicitem"
            ),
        ),
        migrations.AddConstraint(
            model_name="characteristicproduct",
            constraint=models.UniqueConstraint(
                models.F("product"),
                models.F("characteristic"),
                name="unique_product_characteristic",
            ),
        ),
    ]
