# Generated by Django 4.2 on 2023-04-16 11:41

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_characteristicproduct_product_characteristics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="категория",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="characteristicproduct",
            options={
                "verbose_name": "характеристика модели",
                "verbose_name_plural": "характеристики модели",
            },
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.characteristicgroup",
                verbose_name="группа характеристик",
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Элемент списка"), (2, "Измерение")],
                null=True,
                validators=[main.models.is_nul_validator],
                verbose_name="тип",
            ),
        ),
        migrations.AlterField(
            model_name="characteristicproduct",
            name="characteristic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.characteristicitem",
                verbose_name="характеристика",
            ),
        ),
        migrations.AlterField(
            model_name="characteristicproduct",
            name="value",
            field=models.IntegerField(blank=True, null=True, verbose_name="значение"),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": (
                    "super_category__order",
                    "super_category__title",
                    "order",
                    "title",
                ),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.category",),
        ),
        migrations.CreateModel(
            name="SuperCategory",
            fields=[],
            options={
                "verbose_name": "группа гатегорий",
                "verbose_name_plural": "группы категорий",
                "ordering": ("order", "title"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.category",),
        ),
        migrations.AddField(
            model_name="category",
            name="super_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.supercategory",
                verbose_name="надрубрика",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.subcategory",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
    ]
