# Generated by Django 4.2 on 2023-04-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_user_product_buyers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=150, verbose_name="автор")),
                (
                    "is_anonimous",
                    models.BooleanField(
                        default=False, verbose_name="оставаться анонимным?"
                    ),
                ),
                ("content", models.TextField(verbose_name="содержание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="выводить на экран?"
                    ),
                ),
                (
                    "is_claim",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="жалоба"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="опубликован"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
                "ordering": ["created_at"],
            },
        ),
    ]
