# Generated by Django 4.2 on 2023-04-29 07:48

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CharacteristicProduct",
            new_name="CharacteristicProductRelated",
        ),
        migrations.AlterField(
            model_name="additionalimage",
            name="image",
            field=models.ImageField(
                upload_to=main.utilities.get_timestamp_path,
                verbose_name="дополнительное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_claim",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="жалоба"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=main.utilities.get_timestamp_path,
                verbose_name="основное изображение",
            ),
        ),
    ]
