# Generated by Django 4.2 on 2023-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advanceduser",
            name="is_activated",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="прошел активацию"
            ),
        ),
    ]
