# Generated by Django 4.2 on 2023-04-15 08:17

import advuser.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advuser", "0002_alter_advanceduser_is_activated"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="advanceduser",
            managers=[
                ("objects", advuser.models.AdvancedUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="advanceduser",
            name="is_activated",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="прошел активацию"
            ),
        ),
    ]
